In [4]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in .\AppData\Roaming\Python\Python313\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd

print(pd.__version__)

3.0.3

In [7]:
import pandas as pd
data={
"Name":["Sreehari","Krishna","Anugraha","Aby"],
"Age":[20,21,22,23]
}
df=pd.DataFrame(data)
print(df)

       Name  Age
0  Sreehari   20
1   Krishna   21
2  Anugraha   22
3       Aby   23

In [8]:
import pandas as pd
lst=[['Sreehari',25],['Aby',26]]
df=pd.DataFrame(lst,columns=['Name','Age'])
print(df)

       Name  Age
0  Sreehari   25
1       Aby   26

In [9]:
df['Name']

0    Sreehari
1         Aby
Name: Name, dtype: str

In [10]:
df.iloc[0]

Name    Sreehari
Age           25
Name: 0, dtype: object

# Data Inspection

In [13]:
import pandas as pd
data={
    "Name":["Sreehari","Krishna","Aby","Anugraha","Parvathy","Hena"],
    "Age":[20,21,22,23,24,25],
    "Marks":[90,95,91,92,93,92]
}
df=pd.DataFrame(data)
df.head()

       Name  Age  Marks
0  Sreehari   20     90
1   Krishna   21     95
2       Aby   22     91
3  Anugraha   23     92
4  Parvathy   24     93

In [14]:
df.head(3)

       Name  Age  Marks
0  Sreehari   20     90
1   Krishna   21     95
2       Aby   22     91

In [15]:
df.tail()

       Name  Age  Marks
1   Krishna   21     95
2       Aby   22     91
3  Anugraha   23     92
4  Parvathy   24     93
5      Hena   25     92

In [16]:
df.tail(2)

       Name  Age  Marks
4  Parvathy   24     93
5      Hena   25     92

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     6 non-null      int64
 2   Marks   6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 276.0 bytes

In [18]:
df.describe()

             Age      Marks
count   6.000000   6.000000
mean   22.500000  92.166667
std     1.870829   1.722401
min    20.000000  90.000000
25%    21.250000  91.250000
50%    22.500000  92.000000
75%    23.750000  92.750000
max    25.000000  95.000000

In [19]:
import pandas as pd

data = {
    "Name":["Sreehari","Arun","Vishnu","Rahul","Anu"],
    "Marks":[90,85,88,92,87]
}

df = pd.DataFrame(data)

print(df.head())

print("\n")
print(df.tail())

print("\n")
df.info()

print("\n")
print(df.describe())

       Name  Marks
0  Sreehari     90
1      Arun     85
2    Vishnu     88
3     Rahul     92
4       Anu     87


       Name  Marks
0  Sreehari     90
1      Arun     85
2    Vishnu     88
3     Rahul     92
4       Anu     87


<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Marks   5 non-null      int64
dtypes: int64(1), str(1)
memory usage: 212.0 bytes


           Marks
count   5.000000
mean   88.400000
std     2.701851
min    85.000000
25%    87.000000
50%    88.000000
75%    90.000000
max    92.000000

# Selecting Data

In [20]:
import pandas as pd
data={
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 22],
    "Marks": [90, 85, 88]
}
df=pd.DataFrame(data)
print(df)

      Name  Age  Marks
0    Alice   25     90
1      Bob   30     85
2  Charlie   22     88

In [23]:
df['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [24]:
df['Age']

0    25
1    30
2    22
Name: Age, dtype: int64

In [25]:
df[['Name','Age']]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   22

In [26]:
df.loc[0]

Name     Alice
Age         25
Marks       90
Name: 0, dtype: object

In [27]:
df.loc[1]

Name     Bob
Age       30
Marks     85
Name: 1, dtype: object

In [28]:
df.iloc[0]

Name     Alice
Age         25
Marks       90
Name: 0, dtype: object

In [29]:
df.iloc[1]

Name     Bob
Age       30
Marks     85
Name: 1, dtype: object

In [30]:
df.loc[0, 'Name']

'Alice'

In [31]:
df.iloc[0, 1]

np.int64(25)

In [32]:
df.loc[0:1]

    Name  Age  Marks
0  Alice   25     90
1    Bob   30     85

In [33]:
df.iloc[0:2]

    Name  Age  Marks
0  Alice   25     90
1    Bob   30     85

# Filtering Data

In [34]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 22, 28],
    "Marks": [90, 85, 88, 92]
}

df = pd.DataFrame(data)

print(df)

      Name  Age  Marks
0    Alice   25     90
1      Bob   30     85
2  Charlie   22     88
3    David   28     92

In [35]:
# Age greater than 25

In [36]:
df[df['Age']>25]

    Name  Age  Marks
1    Bob   30     85
3  David   28     92

In [37]:
# Marks greater than 88

In [38]:
df[df['Marks']>88]

    Name  Age  Marks
0  Alice   25     90
3  David   28     92

In [41]:
#Age equal to 30

In [40]:
df[df['Age']==30]

  Name  Age  Marks
1  Bob   30     85

In [42]:
# Age not equal to 25

In [43]:
df[df['Age']!=25]

      Name  Age  Marks
1      Bob   30     85
2  Charlie   22     88
3    David   28     92

In [44]:
df[(df['Age'] > 25) & (df['Marks'] > 85)]

    Name  Age  Marks
3  David   28     92

In [45]:
df[(df['Age'] > 25) | (df['Marks'] > 90)]

    Name  Age  Marks
1    Bob   30     85
3  David   28     92

In [46]:
#Students with Age > 25, show only Name:

In [47]:
df[df['Age'] > 25]['Name']

1      Bob
3    David
Name: Name, dtype: str

In [48]:
import pandas as pd
data={
    "Name":["Alice", "Bob"],
    "Age": [25, 30]
}

df = pd.DataFrame(data)

print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [49]:
#adding new column

In [52]:
import pandas as pd
data={
    "Name":["Alice", "Bob"],
    "Age": [25, 30]
}

df = pd.DataFrame(data)

print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [54]:
#df['Column_Name']=values

In [56]:
df['Gender']=['F','M']
print(df)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [58]:
df['Marks']=[95,88]
print(df)

    Name  Age Gender  Marks
0  Alice   25      F     95
1    Bob   30      M     88

In [59]:
# removing a column

In [60]:
import pandas as pd
data={
    "Name":["Alice", "Bob"],
    "Age": [25, 30]
}

df = pd.DataFrame(data)

print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [61]:
#df.drop('Column_Name', axis=1)

In [62]:
df.drop('Age',axis=1)

    Name
0  Alice
1    Bob

In [64]:
#axis=0 → Rows
#axis=1 → Columns

In [67]:
import pandas as pd
data={
    "Name":["Alice", "Bob"],
    "Age": [25, 30]
}

df = pd.DataFrame(data)
df['Gender']=['F','M']


print(df)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

# Handling Missing Data

In [1]:
import pandas as pd
import numpy as np
data={
    "Name":["Alice", "Bob", "Charlie"],
    "Age": [25, np.nan, 22],
    "Marks": [90, 85, np.nan]
}

df = pd.DataFrame(data)

print(df)

      Name   Age  Marks
0    Alice  25.0   90.0
1      Bob   NaN   85.0
2  Charlie  22.0    NaN

In [2]:
#NaN = Not a Number
#It represents a missing value.

In [3]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, np.nan, 22],
    "Marks": [90, 85, np.nan]
}

df = pd.DataFrame(data)

print(df)

      Name   Age  Marks
0    Alice  25.0   90.0
1      Bob   NaN   85.0
2  Charlie  22.0    NaN

In [4]:
df.isnull()

    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True

In [5]:
#False = Value exists
#True  = Value is missing

In [6]:
df.isnull().sum()

Name     0
Age      1
Marks    1
dtype: int64

In [7]:
df.dropna()

    Name   Age  Marks
0  Alice  25.0   90.0

In [8]:
# to save permenantly
#df.dropna(inplace=True)

In [10]:
df.fillna(0)

      Name   Age  Marks
0    Alice  25.0   90.0
1      Bob   0.0   85.0
2  Charlie  22.0    0.0

In [11]:
df.fillna(100)

      Name    Age  Marks
0    Alice   25.0   90.0
1      Bob  100.0   85.0
2  Charlie   22.0  100.0

In [12]:
# fill with mean

In [13]:
df['Age'].fillna(df['Age'].mean())

0    25.0
1    23.5
2    22.0
Name: Age, dtype: float64

# Grouping and aggregating

In [14]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Gender": ["F", "M", "M", "F"],
    "Age": [25, 30, 22, 28]
}

df = pd.DataFrame(data)

print(df)

      Name Gender  Age
0    Alice      F   25
1      Bob      M   30
2  Charlie      M   22
3    David      F   28

In [15]:
df.groupby('Gender')['Age'].mean()

Gender
F    26.5
M    26.0
Name: Age, dtype: float64

In [16]:
df.groupby('Gender')['Age'].sum()

Gender
F    53
M    52
Name: Age, dtype: int64

In [17]:
df.groupby('Gender')['Age'].count()

Gender
F    2
M    2
Name: Age, dtype: int64

In [18]:
df.groupby('Gender')['Age'].max()

Gender
F    28
M    30
Name: Age, dtype: int64

In [19]:
df.groupby('Gender')['Age'].min()

Gender
F    25
M    22
Name: Age, dtype: int64

In [20]:
df.groupby('Gender')['Age'].agg(['mean','max','min','count'])

        mean  max  min  count
Gender
F       26.5   28   25      2
M       26.0   30   22      2

# Merging and Joining

In [22]:
import pandas as pd

df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Marks': [90, 85, 88]
})

In [23]:
pd.merge(df1, df2, on='ID')

   ID     Name  Marks
0   1    Alice     90
1   2      Bob     85
2   3  Charlie     88

In [24]:
#on='ID'
#Match rows where ID is the same.

In [25]:
df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob']
})

df2 = pd.DataFrame({
    'Marks': [90, 85]
})

In [26]:
df1.join(df2)

    Name  Marks
0  Alice     90
1    Bob     85

# Reading and Writing files

In [28]:
#import pandas as pd

#df = pd.read_csv('data.csv')

# Usefull functions

In [31]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice"],
    "Age": [25, 30, 22, 25]
}

df = pd.DataFrame(data)

print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   22
3    Alice   25

In [32]:
df.sort_values('Age')

      Name  Age
2  Charlie   22
0    Alice   25
3    Alice   25
1      Bob   30

In [33]:
df.sort_values('Age', ascending=False)

      Name  Age
1      Bob   30
0    Alice   25
3    Alice   25
2  Charlie   22

In [34]:
df['Age'].apply(lambda x: x + 1)

0    26
1    31
2    23
3    26
Name: Age, dtype: int64

In [35]:
df['Age'] = df['Age'].apply(lambda x: x + 1)

In [36]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob', 'Charlie']
Length: 3, dtype: str

In [37]:
df['Name'].value_counts()

Name
Alice      2
Bob        1
Charlie    1
Name: count, dtype: int64

In [38]:
df['Age'].value_counts()

Age
26    2
31    1
23    1
Name: count, dtype: int64